### ISSUE TITLE
Settings and configuration

### ISSUE THREAD

**Issue by jbnv** [slang800/atom-tidy-markdown#34] opened 2016-01-21 03:23 UTC
I would use this, but there are two major problems with it for me. First, it removes blank lines between headers and the paragraphs beneath them. I intentionally put this whitespace in to improve readibility. Second, it removes whitespace between bullet items. I have many cases where I intentionally space between bullets. 

These are matters of personal taste, so I propose that these sorts of actions be configurable. Develop a Settings page and add options for things as they are requested.

**Comment by notslang** [comment] 2016-01-27 02:10
closing as a dupe of https://github.com/slang800/tidy-markdown/issues/6

**Closed as completed by notslang** 2016-01-27 02:10 UTC
