### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by gcman105** [slang800/atom-tidy-markdown#4] opened 2015-03-19 10:55 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
new TidyMarkdown (/Users/gcman105_mbp/.atom/packages/tidy-markdown/lib/tidy-markdown.coffee:11:29)
```

**Comment by notslang** [comment] 2015-03-27 02:10
duplicate of #2, which I think I fixed in v0.2.0, but feel free to reopen if you're still getting this after updating.

**Closed as completed by notslang** 2015-03-27 02:10 UTC
