### ISSUE TITLE
HTML attributes stripped when converted to Markdown

### ISSUE THREAD

**Issue by ghost** [slang800/atom-tidy-markdown#54] opened 2016-07-04 09:57 UTC
As it's currently not possible to control an image size in pure Markdown, it seems that the only way to go about it is to use:
`<img src="image.jpg" width="100" />`

When running tidy markdown on the file however, it converts this `<img>` HTML tag to the standard markdown syntax `![](image.jpg)`, and gets rid of the width attribute in the process. 

I think that makes sense since HTML within Markdown is not considered good design, but it would be great to at least have the option to disable HTML tag conversion into Markdown in the package settings - I absolutely have to control image size in the Markdown file I'm currently working on, and as such, I can't use Tidy Markdown at all!

**Comment by notslang** [comment] 2016-07-05 10:07
Closing as dupe of https://github.com/slang800/tidy-markdown/issues/28 (which I'd totally take a PR for)

Also, I would recommend you use CSS to control the size of your images, since image size is style, not content... Or if you're doing it for performance reasons then add the image sizes by post-processing the HTML.

**Closed as completed by notslang** 2016-07-05 10:07 UTC

**Comment by ghost** [comment] 2016-07-06 01:58
Noted, thanks for the tip! I'll try and find a workaround like this.
