### ISSUE TITLE
Auto fix list number crosses headers

### ISSUE THREAD

**Issue by yantongl** [slang800/atom-tidy-markdown#8] opened 2015-03-26 17:53 UTC
I have some ordered list, whose numbers are auto changed to be wrong number. For example, my case might looks like:

```
# H1 header
1. blah
2. blah
3. blah

# another H1  header
1. blah
2. blah
```

tidy-markdown change my numbers in 2nd list to be "4." and "5.". It looks really confusing and wrong. Ordered list in different groups should not interrupt each other, even separated by simply an empty line. Please fix it!

Also, I really like auto fix table, but don't like auto remove empty lines. Can we have a setting to enable selected features?

Thanks!

**Comment by notslang** [comment] 2015-03-26 19:37
> I have some ordered list, whose numbers are auto changed to be wrong number.

closing as a duplicate of #7 (which I just pushed a fix for)

> Also, I really like auto fix table, but don't like auto remove empty lines.

Is there a reason why you want empty lines?

**Closed as completed by notslang** 2015-03-26 19:37 UTC
