### ISSUE TITLE
Uncaught mapping values are not allowed here  on line 1, column 19

### ISSUE THREAD

**Issue by nmenag** [slang800/atom-tidy-markdown#13] opened 2015-07-16 03:47 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [tidy-markdown](https://github.com/slang800/atom-tidy-markdown) package, v1.0.0
### Stack Trace

Uncaught mapping values are not allowed here
  on line 1, column 19

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:774

mapping values are not allowed here
  on line 1, column 19
    at ScannerError.YAMLError (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:70:46)
    at ScannerError.MarkedYAMLError (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:90:45)
    at new ScannerError (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:23:49)
    at Constructor.Scanner.Scanner.fetch_value (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:505:19)
    at Constructor.Scanner.Scanner.fetch_more_tokens (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:215:21)
    at Constructor.Scanner.Scanner.check_token (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/scanner.js:116:14)
    at Constructor.Parser.Parser.parse_block_mapping_key (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:422:16)
    at Constructor.Parser.Parser.check_event (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/parser.js:62:48)
    at Constructor.Composer.Composer.compose_mapping_node (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:144:20)
    at Constructor.Composer.Composer.compose_node (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:92:21)
    at Constructor.Composer.Composer.compose_document (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:65:19)
    at Constructor.Composer.Composer.get_single_node (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/composer.js:52:25)
    at Constructor.BaseConstructor.BaseConstructor.get_single_data (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:77:19)
    at Object.load (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/node_modules/yaml-js/lib/yaml.js:112:20)
    at parse (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:28:27)
    at extractor (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/node_modules/front-matter/index.js:21:34)
    at module.exports (/Users/nmenag/.atom/packages/tidy-markdown/node_modules/tidy-markdown/lib/index.coffee:303:15)
    at Object.module.exports.run (/Users/nmenag/.atom/packages/tidy-markdown/lib/index.coffee:70:19)
    at /Users/nmenag/.atom/packages/tidy-markdown/lib/index.coffee:45:28
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
    at /Users/nmenag/.atom/packages/tidy-markdown/lib/index.coffee:43:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:985:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:535:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:518:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:592:35)
    at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:311:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```
### Commands

```
     -0:15.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:11.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:11 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:09.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:09.9.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.0 core:paste (atom-text-editor.editor.is-focused)
     -0:04.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.9
autocomplete-php, v0.3.6
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
bug-report, v0.7.1
color-picker, v2.0.10
css-snippets, v0.8.0
emmet, v2.3.12
highlight-line, v0.11.0
linter, v1.2.4
markdown-format, v2.5.1
markdown-writer, v1.6.0
minimap, v4.11.2
monokai, v0.14.0
project-manager, v1.15.11
seti-ui, v0.7.1
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by nmenag** [comment] 2015-07-16 03:51
When use jekyll http://jekyllrb.com/ ,i returns this error.

**Comment by notslang** [comment] 2015-07-16 20:37
dupe of #12

**Closed as completed by notslang** 2015-07-16 20:37 UTC

**Comment by nmenag** [comment] 2015-07-19 20:20
solved, unistall package https://github.com/slang800/atom-tidy-markdown

**Comment by notslang** [comment] 2015-07-20 14:56
Haha, true - that'll solve it :wink:
